<?php

require_once dirname(__FILE__) . '/../../domain/domain_ObjectWatcher.php';

/**
 * Test class for domain_ObjectWatcher.
 * Generated by PHPUnit on 2010-11-11 at 16:11:15.
 */
class domain_ObjectWatcherTest extends PHPUnit_Framework_TestCase {

    /**
     * @var domain_ObjectWatcher
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new domain_ObjectWatcher;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testInstance().
     */
    public function testInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAdd().
     */
    public function testAdd() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testExists().
     */
    public function testExists() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
