<?php

//require_once dirname(__FILE__) . '/../../domain/domain_Post.php';

/**
 * Test class for domain_Post.
 * Generated by PHPUnit on 2010-11-11 at 13:44:18.
 */
class domain_PostTest extends PHPUnit_Framework_TestCase {

    /**
     * @var domain_Post
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new domain_Post;
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testGetName().
     */
    public function testSetGetName() {
        $this->object->setName('test');
        $this->assertEquals($this->object->getName(), 'test');
        // Remove the following lines when you implement this test.
        //$this->markTestIncomplete(
        //        'This test has not been implemented yet.'
        //);
    }

    /**
     * @todo Implement testGetContent().
     */
    public function testSetGetContent() {
        // Remove the following lines when you implement this test.
        $this->object->setContent('content');
        $this->assertEquals($this->object->getContent(), 'content');
    }

    /**
     * @todo Implement testSetContent().
     */
    public function testSetContent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    public function testSetAndGetIdUser() {
        $this->object->setIdUser(77);
        $this->assertEquals($this->object->getIdUser(),77);
    }

    public function testSetAndGetCreateDate() {
        $this->object->setCreateDate( date('d-m-y') );
        $this->assertEquals( $this->object->getCreateDate(), date('d-m-y') );
    }

   
    /**
     * @todo Implement testGetComments().
     */
    public function testGetComments() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetComments().
     */
    public function testSetComments() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAddComment().
     */
    public function testAddComment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
